"""addPasswordChangedCOlumn

Revision ID: 5832648c54ea
Revises: 01534266fcf1
Create Date: 2026-07-04 11:34:01.159239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5832648c54ea'
down_revision: Union[str, Sequence[str], None] = '01534266fcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password_changed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password_changed_at')
    # ### end Alembic commands ###
