"""UpdatedDB

Revision ID: 8ed4e986b4f3
Revises: 5832648c54ea
Create Date: 2026-07-08 13:26:46.945772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed4e986b4f3'
down_revision: Union[str, Sequence[str], None] = '5832648c54ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('role_id', sa.Integer(), server_default='3', nullable=False))
    op.create_foreign_key(None, 'Users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'role_id')
    # ### end Alembic commands ###
